---
author: Chris Zuber
title: Kern Valley Store
url: https://store.kernvalley.us
markdown: kramdown
version: 1.0.0
timezone: America/Los_Angeles
lang: en
dir: ltr
charset: utf-8
paginate: 8
paginate_path: "/page-:num/"
viewport: "width=device-width, viewport-fit=cover"
robots: 'follow, index'
referrer: no-referrer
manifest: /manifest.json
tiles-config: /browserconfig.xml
service_worker: /service-worker.js
og-type: website
keep-kern-clean: true
description: Online store for Kern Valley souvenirs, clothing, etc.
mobile-web-app-capable: true
canonical: https://store.kernvalley.us
keywords:
  - kernvalley
  - store
  - shopping
  - souvenirs
repository:
  username: kernvalley
  project: store.kernvalley.us
  title: KRV Store
twitter: kern_valley
feed:
  url: /feed.rss
  type: application/rss+xml
icons: /img/icons.svg
# discus-identifier:
# google-analytics:
# ad-sense:
# webmaster-verifications:
#   google:
#   bing:
collections:
  clothing:
    output: true
    permalink: /clothing/:name
    layout: product
  souvenirs:
    output: true
    permalink: /souvenirs/:name
    layout: product
  whiskeyflats:
    output: true
    permalink: /whiskey-flat-days/:name
    layout: product
  derby:
    output: true
    permalink: /fishing-derby/:name
    layout: product
defaults:
  - scope:
      path: _clothing
    values:
      layout: product
      index: true
  - scope:
      path: _souvenirs
    values:
      layout: product
      index: true
  - scope:
      path: _whiskeyflats
    values:
      layout: product
      index: true
  - scope:
      path: _derby
    values:
      layout: product
      index: true
plugins:
  - jekyll-gist
  - jekyll-youtube
  - jekyll-admin
  - jekyll-watch
  - jekyll-paginate
include:
# Folders with dotfiles are ignored by default.
  - .well-known
  - _headers
  - _redirects
exclude:
  - ".gitkeep"
  - "*.rb"
  - "*.gemspec"
  - "*.php"
  - "*.sh"
  - "*.csv"
  - "*.sfd"
  - "*.ai"
  - "*.psd"
  - "*.sketch"
  - "*.yml"
  - "*.lock"
  - "*.log"
  - "*.config.js"
  - ".gitkeep"
  - docs/
  - "/.github/"
  - Gemfile
  - node_modules/
  - palette.xml
  - README.md
  - LICENSE
  - "/img/octicons/*.md"
  - "/img/octicons/LICENSE"
  - "/img/octicons/script"
  - "/img/adwaita-icons/docs"
  - "/img/adwaita-icons/LICENSE"
